2025-04-01 22:14:11 | ERROR    | __main__:<module>:52 - Erro ao iniciar servidor: name 'call_gpt' is not defined
